theme = "lydia"

[editor]
line-number = "relative"
cursorline = false
color-modes = true
auto-save = true
auto-format = true
trim-trailing-whitespace = true
popup-border = "all"
# jump-label-alphabet = "asdflkjwerpio"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.indent-guides]
render = true
character = "â”Š"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "file-base-name", "file-modification-indicator", "spinner"]
center = []
right = ["diagnostics", "version-control", "position"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.normal]
"X" = "extend_line_up"
"S-d" = ":buffer-close"
"ret" = "goto_word"
"}" = ["goto_next_paragraph", "collapse_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"C-y" = [
  ':sh rm -f /tmp/unique-file',
  ':sh rm -f /tmp/unique-cwd-file',
  ":insert-output yazi --chooser-file=/tmp/unique-file --cwd-file=/tmp/unique-cwd-file",
  ':sh printf "\\x1b[?1049h\\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':cd %sh{cat /tmp/unique-cwd-file}',
  ':redraw',
]

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

[keys.normal.space]
"=" = ":format"
